// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SudokuSolver")>]
[<assembly: AssemblyProductAttribute("EmguCvPlayground")>]
[<assembly: AssemblyDescriptionAttribute("EmguCvPlayground")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SudokuSolver"
    let [<Literal>] AssemblyProduct = "EmguCvPlayground"
    let [<Literal>] AssemblyDescription = "EmguCvPlayground"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
